name: Manual workflow
on:
  workflow_dispatch


jobs:
  echo-some-text:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"