name: My Action

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "🎉 The job was automatically triggered by the ${{ github.event_name }} event."
      - run: echo "username = ${{ inputs.username }}"
