name: Install dependencies

on:
  workflow_call:

jobs:
  install-dependencies:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "running npm ci"
      - run: npm install
